#!/bin/bash

# damonnator_test.sh - Continuous E2E Testing Loop
# Usage: ./damonnator_test.sh [iterations]
#
# This script runs the E2E test suite continuously and:
# 1. Executes e2e_runner.py to run tests from e2e-tests.json
# 2. Parses test-results.json to extract test outcomes
# 3. Updates prd.json with test_metadata (last_tested, status, failures)
# 4. Creates GitHub issues when tests fail
#
# Three autonomous loops, three tracking files:
# - damonnator.sh: builds product features from prd.json → progress.txt
# - damonnator_infra.sh: builds test infrastructure from test-prd.json → test-progress.txt
# - damonnator_test.sh: validates features using the test infrastructure → test-results.json

ITERATIONS=${1:-10}
REPO="https://github.com/doogie-bigmack/application-security-policy-miner"

echo ""
echo "=========================================="
echo "🧪 Damonnator Test Runner"
echo "=========================================="
echo "Running E2E test suite from e2e-tests.json"
echo "Repo: $REPO"
echo "Iterations: $ITERATIONS"
echo ""

# Ensure Docker services are running
echo "🐳 Ensuring Docker services are running..."
docker-compose up -d
echo ""

# Wait for services to be healthy
echo "⏳ Waiting for services to be healthy..."
sleep 5
echo ""

for ((i=1; i<=$ITERATIONS; i++)); do
    echo ""
    echo "=========================================="
    echo "Test Iteration $i of $ITERATIONS"
    echo "=========================================="
    echo ""

    TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

    # Run E2E tests using the runner
    echo "🧪 Running E2E test suite..."
    echo ""

    # Use virtual environment Python directly (avoid subshell issues with source)
    if e2e/.venv/bin/python3 -m e2e.e2e_runner --test-suite e2e-tests.json --prd prd.json --output test-results.json; then
        TEST_EXIT_CODE=0
        echo ""
        echo "✅ All tests passed!"
    else
        TEST_EXIT_CODE=$?
        echo ""
        echo "❌ Some tests failed (exit code: $TEST_EXIT_CODE)"
    fi

    echo ""

    # Check if test-results.json was generated
    if [ ! -f test-results.json ]; then
        echo "⚠️  WARNING: test-results.json was not generated"
        echo "Skipping result processing for this iteration"
        continue
    fi

    # Parse test results and display summary
    echo "📊 Test Results Summary:"
    echo "---"

    # Extract summary using jq
    TOTAL_TESTS=$(jq -r '.summary.total_tests // 0' test-results.json)
    PASSED=$(jq -r '.summary.passed // 0' test-results.json)
    FAILED=$(jq -r '.summary.failed // 0' test-results.json)
    SKIPPED=$(jq -r '.summary.skipped // 0' test-results.json)
    PASS_RATE=$(jq -r '.summary.pass_rate // 0' test-results.json)

    echo "Total Tests: $TOTAL_TESTS"
    echo "Passed: $PASSED"
    echo "Failed: $FAILED"
    echo "Skipped: $SKIPPED"
    echo "Pass Rate: $PASS_RATE%"
    echo ""

    # If there are failures, show details
    if [ "$FAILED" -gt 0 ]; then
        echo "❌ Failed Tests:"
        jq -r '.test_results[] | select(.status == "failed") | "  - \(.test_id): \(.error.message // "Unknown error")"' test-results.json
        echo ""

        echo "💡 Recommendations:"
        jq -r '.recommendations[]? // empty' test-results.json | sed 's/^/  - /'
        echo ""

        # Create GitHub issue for test failures
        echo "🐛 Creating GitHub issue for test failures..."
        ISSUE_TITLE="E2E Test Failures - $(date +"%Y-%m-%d %H:%M")"
        ISSUE_BODY="## Test Failure Report

**Test Run:** $TIMESTAMP
**Failed Tests:** $FAILED / $TOTAL_TESTS
**Pass Rate:** $PASS_RATE%

### Failed Tests
$(jq -r '.test_results[] | select(.status == "failed") | "- **\(.test_id)**: \(.error.message // "Unknown error")\n  - Error Type: \(.error.type // "unknown")\n  - Step: \(.error.step_index // "N/A") - \(.error.step_description // "N/A")\n"' test-results.json)

### Recommendations
$(jq -r '.recommendations[]? // "No recommendations available"' test-results.json | sed 's/^/- /')

### Coverage Analysis
- PRD Stories Tested: $(jq -r '.coverage_analysis.prd_stories_tested // 0' test-results.json)
- Total PRD Stories: $(jq -r '.coverage_analysis.prd_stories_total // 0' test-results.json)
- Coverage: $(jq -r '.coverage_analysis.coverage_percentage // 0' test-results.json)%

### Untested Stories
$(jq -r '.coverage_analysis.untested_stories[]? // "All stories covered"' test-results.json | sed 's/^/- /')

---
Generated by damonnator_test.sh
Test Results: test-results.json"

        # Create issue (only if gh is available and we're in a git repo)
        if command -v gh &> /dev/null && git rev-parse --is-inside-work-tree &> /dev/null; then
            gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --label "e2e-test-failure,automated" 2>/dev/null || echo "⚠️  Could not create GitHub issue (may need authentication)"
        else
            echo "⚠️  GitHub CLI not available or not in a git repo, skipping issue creation"
        fi
        echo ""
    fi

    # Update prd.json with test metadata
    echo "📝 Updating prd.json with test metadata..."

    # Create a temporary file for the updated prd.json
    TEMP_PRD=$(mktemp)

    # Use jq to update prd.json with test metadata from test-results.json
    jq --slurpfile results test-results.json '
        .stories |= map(
            . as $story |
            ($results[0].test_results[] | select(.prd_story_id == $story.id)) as $test |
            if $test then
                . + {
                    test_metadata: {
                        last_tested: $results[0].metadata.started_at,
                        test_status: $test.status,
                        test_duration_seconds: $test.duration_seconds,
                        last_failure: (if $test.status == "failed" then $test.error.message else null end)
                    }
                }
            else
                .
            end
        )
    ' prd.json > "$TEMP_PRD"

    # Replace prd.json with updated version
    mv "$TEMP_PRD" prd.json
    echo "✅ prd.json updated with test metadata"
    echo ""

    # Display coverage percentage
    COVERAGE=$(jq -r '.coverage_analysis.coverage_percentage // 0' test-results.json)
    echo "📈 PRD Coverage: $COVERAGE%"
    echo ""

    # Wait before next iteration (unless it's the last one)
    if [ $i -lt $ITERATIONS ]; then
        echo "⏳ Waiting 30 seconds before next iteration..."
        sleep 30
    fi

done

echo ""
echo "=========================================="
echo "✅ Completed $ITERATIONS test iterations"
echo "=========================================="
echo ""

# Show final status
if [ -f test-results.json ]; then
    FINAL_PASS_RATE=$(jq -r '.summary.pass_rate // 0' test-results.json)
    echo "Final Pass Rate: $FINAL_PASS_RATE%"

    if [ "$FINAL_PASS_RATE" == "100" ]; then
        osascript -e 'display notification "All E2E tests passing!" with title "Damonnator Test" sound name "Glass"' 2>/dev/null || true
    else
        osascript -e 'display notification "Some tests are failing" with title "Damonnator Test" sound name "Ping"' 2>/dev/null || true
    fi
fi
